services:
  postgres:
    container_name: postgres-sql-tata-fne
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: tata_fne_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
#  pgadmin:
#    container_name: pgadmin4-cinema
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - 8081:80
#    depends_on:
#      - postgres
#    networks:
#      - spring-demo
#    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-tata-fne
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
